# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2024-08-22 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('velocity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='velocity',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
